### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by petrichbg** [Fenrirthviti/stream-site#12]
Warning: simplexml_load_file(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /var/www/html/lib/rtmp.class.php on line 88

Warning: simplexml_load_file(): Failed to enable crypto in /var/www/html/lib/rtmp.class.php on line 88

Warning: simplexml_load_file(https://192.168.7.13/stat.xml): failed to open stream: operation failed in /var/www/html/lib/rtmp.class.php on line 88

Warning: simplexml_load_file(): I/O warning : failed to load external entity "https://192.168.7.13/stat.xml" in /var/www/html/lib/rtmp.class.php on line 88

can u help me ?

**Comment by Fenrirthviti** [comment]
Looks like you have an issue with your SSL certificate. You can either not use SSL or reissue a proper certificate.

**Comment by sioliox** [comment]
So ssl is a mist for the site to work .
Does support origin edge server load balancing ?

**Comment by Fenrirthviti** [comment]
No, you don't need SSL for the site to work. You can update the nginx configuration to not use SSL.

Any kind of load balancing would need to be implemented on the nginx side, and is outside the scope of this project.

**Comment by Fenrirthviti** [comment]
Closing as this is just an nginx config issue.
