### ISSUE TITLE
Support for avconv

### ISSUE THREAD

**Issue by kinosang** [Fenrirthviti/stream-site#14]
ffmpeg is not alienable in official Ubuntu repos for 14.04

**Comment by kinosang** [comment]
I've tried `avconv -ss 00:00:00 -i rtmp://localhost/live/$1 -vsync 1 -t 0.01 -f image2 /var/www/img/channel/channel_$1.png` but it not work.

**Comment by Fenrirthviti** [comment]
I have no interest in supporting avconv, so I'm not sure how you would be able to get it to work. 

The proper ffmpeg is available via Ubuntu on 15.04+, otherwise I suggest you update Ubuntu or manually compile per https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

**Comment by kinosang** [comment]
I've compiled ffmpeg manually, it works well.
