### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by petrichbg** [Fenrirthviti/stream-site#16]
hello 
where is chat database.sql ? 

how to add chat table ?

**Comment by Fenrirthviti** [comment]
Apologies, I forgot to upload the sql task to create the chat table. I'll take care of it later tonight or you can manually create the table with 

name **chat**

column name - type:
id - serial (PK)
channel_email - text
sender - text
message - text
timestamp - bigint
type - text

Also, you will need to create a user with display name of GlobalChatChannel to store the global chat messages in. This will also be corrected in later versions, chat is still a work in progress.

**Comment by petrichbg** [comment]
thanks i will test now ;)

**Comment by Fenrirthviti** [comment]
Going to assume this worked, closing.
