### ISSUE TITLE
sql import error

### ISSUE THREAD

**Issue by kimmoda** [Fenrirthviti/stream-site#20]
Hello , ı some sql import error.

**Comment by Fenrirthviti** [comment]
Can you provide the full error, and on which .sql file you get it on?

Also, which version of PGSQL are you using?

**Comment by kimmoda** [comment]
SQL hatası:

ERROR:  syntax error at or near "CREATE"
LINE 5: CREATE TABLE subscribers
        ^
Üstteki hata, aşağıdaki ifade içinde oluştu:

SELECT COUNT(*) AS total FROM (-- Table: subscribers

-- DROP TABLE subscribers;

CREATE TABLE subscribers
(
  host_account text NOT NULL,
  subscriber text NOT NULL,
  CONSTRAINT subscribers_pk PRIMARY KEY (host_account, subscriber),
  CONSTRAINT host_account_fk FOREIGN KEY (host_account)
      REFERENCES users (email) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
)
WITH (
  OIDS=FALSE
);
ALTER TABLE subscribers
  OWNER TO pg_sql_account_here;
COMMENT ON TABLE subscribers
  IS 'Table for managing subscribers for channels') AS sub

**Comment by kimmoda** [comment]
PostgreSQL 8.4.20

**Comment by Fenrirthviti** [comment]
You need to change pg_sql_account_here to your local PostgreSQL account.

**Comment by kimmoda** [comment]
editing , but still this error 

![ss6](https://cloud.githubusercontent.com/assets/24658354/21585740/3f9bbeb0-d0cf-11e6-8b69-c8659682101c.PNG)

CREATE TABLE subscribers ( host_account text NOT NULL, subscriber text NOT NULL, CONSTRAINT subscribers_pk PRIMARY KEY (host_account, subscriber), CONSTRAINT host_account_fk FOREIGN KEY (host_account) REFERENCES users (email) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE ) WITH ( OIDS=FALSE )

MySQL çıktısı: Belgeler

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(
  OIDS=FALSE
)' at line 10


my sql 

-- Table: subscribers

-- DROP TABLE subscribers;

CREATE TABLE subscribers
(
  host_account text NOT NULL,
  subscriber text NOT NULL,
  CONSTRAINT subscribers_pk PRIMARY KEY (host_account, subscriber),
  CONSTRAINT host_account_fk FOREIGN KEY (host_account)
      REFERENCES users (email) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
)
WITH (
  OIDS=FALSE
);
ALTER TABLE subscribers
  OWNER TO admin_1;
COMMENT ON TABLE subscribers
  IS 'Table for managing subscribers for channels';

**Comment by kimmoda** [comment]
![error](https://cloud.githubusercontent.com/assets/24658354/21585777/d2ee8bca-d0cf-11e6-94ab-f79bad7788f6.PNG)

**Comment by Fenrirthviti** [comment]
I've just tested creating a new table using this exact query with no errors.

![success](https://pub.rachni.com/img/pgadmin3_2017-01-02_01-48-32.png)

**Comment by Fenrirthviti** [comment]
It looks like whatever editor/administration tool that you're using is causing the problem. I would recommend trying to import directly from CLI or pgAdmin III if possible.

**Comment by kimmoda** [comment]
this is my line 

-- Table: subscribers

-- DROP TABLE subscribers;

  host_account text NOT NULL,
  subscriber text NOT NULL,
  CONSTRAINT subscribers_pk PRIMARY KEY (host_account, subscriber),
  CONSTRAINT host_account_fk FOREIGN KEY (host_account)
      REFERENCES users (email) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE

WITH (
  OIDS=FALSE

ALTER TABLE subscribers
  admin_test
COMMENT ON TABLE subscribers
  IS 'Table for managing subscribers for channels';

and ı get this error:

![admin](https://cloud.githubusercontent.com/assets/24658354/21585869/3479974e-d0d1-11e6-9280-9036bcdcb591.PNG)

**Comment by Fenrirthviti** [comment]
You're missing a lot of () and ; from the original command if that's exactly what you're putting in. Syntax is very important, you can't remove the command characters.

**Comment by Fenrirthviti** [comment]
Closing as this is an install issue and not a problem with the site itself.
