### ISSUE TITLE
verify account button not working

### ISSUE THREAD

**Issue by kimmoda** [Fenrirthviti/stream-site#21]
![sws](https://cloud.githubusercontent.com/assets/24658354/21587828/3ec44b46-d0e9-11e6-9178-976e21492aaf.PNG)

this blue button not functionally , ı cant click this button.

**Comment by petrichbg** [comment]
Now I tried in my work without problem

**Comment by kimmoda** [comment]
in my case ı have a many problem

**Comment by kimmoda** [comment]
this is my part 

http://jetgez.com/login

404 not found.

**Comment by petrichbg** [comment]
http://galaxy.net-plus.bg:8000 

this is my now i try to reg new user no problem 

https://galaxy.net-plus.bg/login/verify/galina62@mail.bg/05e07bea4a90040e29f40f131aae57469a08b52c7adaf026a78a45ac34df8b04

**Comment by kimmoda** [comment]
cool , you can help for installation ?

**Comment by petrichbg** [comment]
to say what can I help you?

**Comment by kimmoda** [comment]
ı upload project files in my vds account server and ı make database confugration but my login page not showing Where do i make mistakes . this is my test page

http://jetgez.com/login

**Comment by petrichbg** [comment]
you need to configure nginx with all module and use php7 !!! 

see this https://github.com/Fenrirthviti/stream-site/blob/master/src/nginx/sites-available/main.conf

**Comment by petrichbg** [comment]
`# This server block is used as a proxy to enable the on_publish directive to access an SSL page, as it doesn't directly support it. 
# If you're not using SSL, you can remove this block and simply point to the streamauth.php on line 27 of /conf.d/rtmp.conf
server {
	listen 8020;
        location /on_publish {
		#allow 127.0.0.1;
		allow all;
		deny all;
                proxy_pass https://galaxy.net-plus.bg/lib/streamauth.php;
        }

}

# This block enforces SSL. If you're not using SSL, you can remove it and change the next server block to listen over port 80.
server {
	listen       8000;
	server_name    galaxy.net-plus.bg _ 192.168.7.143;
	return         301 https://$host$request_uri;
}

server {
		listen   443 ssl;

		server_name     galaxy.net-plus.bg _ 192.168.7.143;

        ssl on;
   ssl_certificate /etc/letsencrypt/live/galaxy.net-plus.bg/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/galaxy.net-plus.bg/privkey.pem;
   ssl_session_cache shared:SSL:10m;
   ssl_session_timeout 5m;
   ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
   ssl_prefer_server_ciphers on;
   ssl_dhparam /etc/ssl/certs/dhparam.pem;
   ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';


		
		# adjust root directory as needed
		root /var/www/html;
		index index.php index.html index.htm;

try_files $uri $uri/ /index.php?$args;


		location / {
				# This should allow the content to be retrieved from any location. If you're using this internally, you can probably remove most of this.
				add_header 'Access-Control-Allow-Origin' '*';
				add_header 'Access-Control-Expose-Headers' 'Content-Length';
				add_header 'Access-Control-Allow-Headers' 'Range';
				if ($request_method = 'OPTIONS') {
						add_header 'Access-Control-Allow-Origin' '*';
						add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
						#
						# Custom headers and headers various browsers *should* be OK with but aren't
						#
						add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
						#
						# Tell client that this pre-flight info is valid for 20 days
						#
						add_header 'Access-Control-Max-Age' 1728000;
						add_header 'Content-Type' 'text/plain charset=UTF-8';
						add_header 'Content-Length' 0;
						return 204;
				}
				if ($request_method = 'POST') {
						add_header 'Access-Control-Allow-Origin' '*';
						add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
						add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
				}
				if ($request_method = 'GET') {
						add_header 'Access-Control-Allow-Origin' '*';
						add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
						add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
				}

				# rewrite for pretty URLs. This is REQUIRED.
				rewrite /(.*)$ / break;
		}

		# php processor
		location ~ \.php$ {
				try_files $uri =404;
				fastcgi_pass 127.0.0.1:9000;
				fastcgi_index index.php;
				fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
				include fastcgi_params;
		}

		# Rewrite for index, popout player, reset form, and REST API. REQUIRED.
		rewrite /login(.*)$ /login.php last;
		rewrite /popout/(.*)$ /lib/popout.php last;
		rewrite /lostpass(.*)$ /reset.php last;
		rewrite /api/(.*)$ /api/index.php last;
		
		# exclude our data locations from URL rewrite. REQUIRED.
		location /css { }
		location /img { }
		location /inc { }
		location /js { }
		location /lib { }
		location /xsl { }
		location /profiles { }
		location /favicon.ico { }

		# Serve recorded sessions
		location /rec {
				root /var/tmp;
				autoindex off; # directory list prevented. Enable this if you want to see all your recordings at your.site/rec
		}

		# RTMP Stat
		location /stat {
				rtmp_stat all;
				rtmp_stat_stylesheet stat.xsl;
		}
		
		location /stat.xsl {
				root /var/www/html/xsl/;
		}

		# RTMP Control
		location /control {
				# add the IPs you want to have access to directly control streams. Minimum required is localhost and the public server IP, which is used by the site itself to start/stop recordings
				allow 127.0.0.1;
				allow all;
				deny all;
				rtmp_control all;
		}
		
		# used to grab viewercount
		location /nclients {
				satisfy any;
				allow all;
				deny all;
				proxy_pass https://galaxy.net-plus.bg/stat;
				xslt_stylesheet /var/www/html/xsl/nclients.xsl app='$arg_app' name='$arg_name';
				add_header Refresh "3; $request_uri";
		}

		# these pages not included, you must supply your own or leverage inc/404.php
		error_page   500 502 503 504  /50x.html;
		location = /50x.html {
				root   html;
		}
 

   # Serve HLS fragments
    location /hls {
        root /var/tmp;
        add_header Cache-Control no-cache;
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
        }
  

    }

    

        location ~ /.well-known {
                allow all;
        }


}

`

this is my nginx site

**Comment by petrichbg** [comment]
Use SSL with or remove it !!!

free-ssl-certificates-lets-encrypt

I hope in the future to add Auto lets-encrypt

**Comment by kimmoda** [comment]
what is your host provider ?

**Comment by kimmoda** [comment]
also thanks for informations.

**Comment by petrichbg** [comment]
i use my hosting 

streaming
Guest OS
Debian GNU/Linux 10 (64-bit)
Compatibility
ESXi 6.5 and later (VM version 13)
VMware Tools
No
CPUs
2
Memory
2 GB

**Comment by kimmoda** [comment]
cool . thanks. pls check your mailbox

**Comment by petrichbg** [comment]
which email ?

**Comment by kimmoda** [comment]
petrichbg@gmail.com

**Comment by Fenrirthviti** [comment]
Closing as this is an install issue and not a problem with the site itself.
