### ISSUE TITLE
Format not supported

### ISSUE THREAD

**Issue by aske1204** [Fenrirthviti/stream-site#23]
Hi, 
I have recently set up a streaming site by using this "guide". When i try to stream, most of the time the stream does not show up under live channels if it does show up i get an error "The media could not be loaded, either because the server or network failed or because the format is not supported". ATM everything is done on a local network on two machines. I hope you can help

**Comment by Fenrirthviti** [comment]
What kind of device are you trying to watch the stream back on? And how are you sending the data to the server (i.e. OBS, XSplit, etc.)?

**Comment by aske1204** [comment]
The default ammount of workers was too low, it is now fixed
