### ISSUE TITLE
[Suggest]Stream Offline Image

### ISSUE THREAD

**Issue by highattack30** [Fenrirthviti/stream-site#26]
will be amazing if function such twitch offer offline image at stream

**Comment by Fenrirthviti** [comment]
This is planned and is part of #5.

I should have time to start working on some of the nicer front-end polish features in the next few weeks.

**Comment by highattack30** [comment]
I mean the channel picture will toggle to on when the streaming shutdown like twitch?

**Comment by Fenrirthviti** [comment]
Yes, that's what the static preview image would be used for. I can probably break it out into two separate images, one for the channel preview while live and one for offline. The system for one allows the other with little effort.

**Comment by Fenrirthviti** [comment]
Updated #5 to better reflect this discussion.

**Comment by Fenrirthviti** [comment]
Finished this feature via https://github.com/Fenrirthviti/stream-site/commit/22b3b5a58ee7ee45577dee87465867799d9b5c2a

You can update and let me know if you run into any issues. Make sure to add the required columns with their default values to your database.
