### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by kimmoda** [Fenrirthviti/stream-site#27]
SQL sorgusu:

-- Table: subscribers
-- DROP TABLE subscribers;
CREATE TABLE subscribers(

host_account TEXT NOT NULL ,
subscriber TEXT NOT NULL ,
CONSTRAINT subscribers_pk PRIMARY KEY ( host_account, subscriber ) ,
CONSTRAINT host_account_fk FOREIGN KEY ( host_account ) REFERENCES users( email ) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
) WITH (
OIDS = FALSE
);

MySQL çıktısı: Belgeler

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(
  OIDS=FALSE
)' at line 14

**Comment by kimmoda** [comment]
#1170 - BLOB/TEXT column 'host_account' used in key specification without a key length

**Comment by Fenrirthviti** [comment]
MySQL is not supported at this time.

The .sql imports are for PostgreSQL only.
