### ISSUE TITLE
stop SSL

### ISSUE THREAD

**Issue by petrichbg** [Fenrirthviti/stream-site#29]
hello again 
pls can you write how to stop SSL configuration ?

i want http:// not https://

**Comment by Fenrirthviti** [comment]
Remove the port 80 redirect to ssl, and remove the ssl config.

**Comment by petrichbg** [comment]
what line need to remove on config ?

**Comment by Fenrirthviti** [comment]
Please read the config files, it's explained there: https://github.com/Fenrirthviti/stream-site/blob/master/src/nginx/sites-available/main.conf#L14

**Comment by petrichbg** [comment]
when i stop SSL i got this error 

 Notice: Undefined index: HTTPS in /var/www/html/inc/config.php on line 23

**Comment by Fenrirthviti** [comment]
Hmm, that shouldn't happen.

Just change line 23 to this:

```
$protocol = 'http://';
```

**Comment by petrichbg** [comment]
lol ;) 
For 3-4 days I was wondering how to fix this 23 line

**Comment by Fenrirthviti** [comment]
Closing as it looks like you got this working.
