### ISSUE TITLE
Route /watch 404

### ISSUE THREAD

**Issue by und3f1ned** [Fenrirthviti/stream-site#33]
Getting 404 when trying to access to /watch/Admin (Admin – my username). I need the page to be always available. Even if the stream is offline. Where can I find something about this page in the code? Your nginx config is a quite messy. I can't figure out about how the user page constructed. Thank you!

**Comment by Fenrirthviti** [comment]
Check your nginx config that you set up the URL rewrites correctly. You don't have to be live for a page to display. I recently added an offline image for streams that are not online, but pages were always available.

See: https://github.com/Fenrirthviti/stream-site/blob/master/src/nginx/shared.conf for my example config on how this can be accomplished.

**Comment by und3f1ned** [comment]
Thank you! Missed this string https://github.com/Fenrirthviti/stream-site/blob/03cc0d74c51e6664896a810fd9cd35d5bf4397a7/src/nginx/shared.conf#L41
