### ISSUE TITLE
Alternative to Flash for viewers

### ISSUE THREAD

**Issue by SoraBytes** [Fenrirthviti/stream-site#34]
Is it possible to have an alternative to just Flash, for the live stream? Such as a fallback to FLV, MP4, or other video formats? It will delay the viewers but, Firefox no longer supports Flash.

**Comment by Fenrirthviti** [comment]
Sure, just enabled HLS in the nginx config, and configure video.js to play the HLS stream instead.

For my purposes, the additional delay is unacceptable so I do not have any provided configurations for it. It is not difficult to set up, though.

**Comment by Fenrirthviti** [comment]
Closing this in favor of #35 which would meet this requirement, and work has been started there.
