### ISSUE TITLE
Update scripts

### ISSUE THREAD

**Issue by Waffleuncle** [Fenrirthviti/stream-site#41]
Is it possible to update your code. 
We would love to try it. 
Or we could pay you as a free-lancer?

**Comment by Fenrirthviti** [comment]
I'm not sure what you mean by update, what do you think needs updating?

**Comment by Waffleuncle** [comment]
Your entire code does not work with the current distributions. 
Ubuntu 20.04 
it can be nice if you update hole script or make installer sh or docker

**Comment by Fenrirthviti** [comment]
You will need to be more specific what exactly is not working. I have been running this code for several years on a production website and it's working fine. I cannot fix anything if you cannot report what is broken.

**Comment by NekoSuneVR** [comment]
he means about hall website code is outdated over 5 to 6 years and wasn't maintained by any others updates. since Site and some code only supported older version ubuntu its not supported 20.04 and my guess him mean as everything you documented setup doesn't support ubuntu 20.04 LTS

and him like have it as docker (Easy setup scripts) then manual install 1 by 1. like `install.sh` or docker wise.

i can go rough details because i dont see any issues as i cant record or used this yet. but i can boot up temp Ubuntu 20.04 over my windows and try install see what wrong with site him found as non documented.

**Comment by Fenrirthviti** [comment]
I am again confused by this. This is a simple website, not an application. It's written in PHP7, and should be compatible with any newer versions of nginx with the http-flv module (neither of which I maintain) and a postgres. There are no real "scripts" or anything to update here. As mentioned in the readme, this is not really provided as an application that you install, and needs to be manually configured for your environment, making the assumptions you understand the basics on how nginx and websites work.

**Comment by Waffleuncle** [comment]
Where I am lost in your explanation is the string configuration part. 
I think you should work on the process a bit more because it is not very complete. 

Do you have any documentation that I can refer to. 

I am already working with PHP_FPM and NGINX via my project but your explanation is confusing me a bit.

**Comment by Fenrirthviti** [comment]
Again, you need to be more specific with what *exactly* you are having issues with. The required configuration is in the readme at the bottom, under the `Installation` section. If you are getting any kind of error messages or if there is any specific configuration you are confused about, it would be helpful for you to be explicit on what that is. I don't know your skill level, and I don't know what exactly is confusing. As someone who has been working with PHP and nginx for several years, everything makes perfect sense to me, so I will need more information before I know what you are confused on.

I am happy to help, but all you're providing is "your directions suck" without being specific on *what* part you are confused by, or *what* errors you're getting when trying to access the website.

**Comment by Waffleuncle** [comment]
No problem, 
This is not what I wanted to say or convey as a message. 
I will see what I can do on my side if I have any mistakes, I will be happy to ask you for help to know where to direct me. 
Thank you also for this beautiful project, it will allow me to learn more

**Comment by Fenrirthviti** [comment]
Thanks, I'm certainly happy to help or assist if there are any actual errors, but this site should run on anything as long as the required nginx modules and a postgres instance are available and configured per the installation directions.
